# Generated by Django 5.1.1 on 2024-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
